// Generated by CoffeeScript 1.11.1
(function() {
  CORE.Unit_Meshes = (function() {
    function Unit_Meshes() {
      this._square = new CORE.Mesh_Unit_Square();
      this._circle = new CORE.Mesh_Unit_Circle();
      this._triangle = new CORE.Mesh_Unit_Triangle();
    }

    Unit_Meshes.prototype.newSquare = function(params) {
      return this._square.clone(params);
    };

    Unit_Meshes.prototype.newCircle = function(params) {
      return this._circle.clone(params);
    };

    Unit_Meshes.prototype.newTriangle = function(params) {
      return this._triangle.clone(params);
    };

    return Unit_Meshes;

  })();

}).call(this);
