// Generated by CoffeeScript 1.11.1
(function() {
  CORE.I_All_Main = (function() {
    function I_All_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
    }

    I_All_Main.prototype.mouse_down = function(event) {};

    I_All_Main.prototype.mouse_up = function(event) {};

    I_All_Main.prototype.mouse_move = function(event) {};

    return I_All_Main;

  })();

}).call(this);
