// Generated by CoffeeScript 1.11.1

/*
 *
 * Global Style objects, including materials for roads, lines, etc.
 *
 * Written by Bryce Summers on 12 - 19 - 2016.
 *
 */

(function() {
  CORE.init_style = function() {
    CORE.style = {
      m_default_fill: new THREE.MeshBasicMaterial({
        color: 0xffffff,
        side: THREE.DoubleSide
      }),
      m_default_line: new THREE.LineBasicMaterial({
        color: 0x000000,
        linewidth: 1
      }),
      c_fill: new THREE.Color(0xbbbbbb),
      c_stroke: new THREE.Color(0x000000)
    };
    return CORE.style.unit_meshes = new CORE.Unit_Meshes();
  };

}).call(this);
